### ISSUE TITLE
Customize BlockNative/Notify styles

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#623]
## Description

We use `blocknative/notify` for transaction push notifications.

<img width="283" alt="Screen Shot 2022-03-02 at 9 41 45 pm" src="https://user-images.githubusercontent.com/94939382/156359562-be60a41b-82d0-4497-94e4-9f8c5eb48ce0.png">

## Proposal

We should customize the style of the notification to match our other styles.

We can do this using the guide here: https://docs.blocknative.com/notify#customizing-css

Example:

```css
.bn-notify-custom .bn-notify-notifications {
  font-family: 'DM Mono', monospace;
}
```
